INSERT INTO pagamentos.roles (id,descricao,name) VALUES
	 (1,'ADMINISTRADOR','ROLE_ADMIN'),
	 (2,'ADVOGADO','ROLE_ADVOG'),
	 (3,'SÍNDICO','ROLE_SINDI'),
	 (4,'SECRETÁRIO','ROLE_SECRE'),
	 (5,'ZELADOR','ROLE_ZELAD'),
	 (6,'FAXINEIRO','ROLE_FAXIN'),
	 (7,'PORTEIRO','ROLE_PORTE'),
	 (8,'SEGURANÇA','ROLE_SEGUR'),
	 (9,'PINTOR','ROLE_PINTO'),
	 (10,'ELETRICISTA','ROLE_ELETR'),
	 (11,'BOMBEIRO-HIDRÁULICO','ROLE_BOMBE'),
	 (12,'PEDREIRO','ROLE_PEDRE'),
	 (13,'NÃO IDENTIFICADO','ROLE_NIDEN');
