INSERT INTO student (address, email, name)
SELECT 
    CONCAT(FLOOR(1 + (RAND() * 999)), ' Main St, City ', FLOOR(1 + (RAND() * 100))) AS address,
    CONCAT('student', FLOOR(1 + (RAND() * 9999)), '@example.com') AS email,
    CONCAT('Student ', FLOOR(1 + (RAND() * 50))) AS name
FROM 
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
     UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) AS tmp1,
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) AS tmp2
LIMIT 50;
